<?php
/**
 * Created by PhpStorm.
 * User => Kioo
 * Date => 03/10/14
 * Time => 16:49
 */

namespace FDP\Dota2StoreBundle\Install;

use Symfony\Component\DependencyInjection\ContainerInterface as Container;

/**
 * Class Items
 * @package FDP\Dota2StoreBundle\Install
 */
class Items {

	public static function createDatabase(Container $container) {
		$dm = $container->get('doctrine_mongodb')->getManager();

		// delete collection item
		$collection = $dm->getDocumentCollection('\FDP\Dota2StoreBundle\Document\Item');
		$collection->remove(array());


		// install all items
		foreach (Items::$listItems as $v) {
			$item = new \FDP\Dota2StoreBundle\Document\Item();
			$item->setId($v["id"]);
			$item->setCodeName($v["codeName"]);
			$item->setLocalizedName($v["localizedName"]);
			$dm->persist($item);
			$item = null;
		}

		$dm->flush();
	}

	public static $listItems = array(
		array("id" => 0, "codeName" => "empty", "localizedName" => "Vide"),
		array("id" => 1, "codeName" => "blink", "localizedName" => "Blink dagger"),
		array("id" => 2, "codeName" => "blades_of_attack", "localizedName" => ""),
		array("id" => 3, "codeName" => "broadsword", "localizedName" => ""),
		array("id" => 4, "codeName" => "chainmail", "localizedName" => ""),
		array("id" => 5, "codeName" => "claymore", "localizedName" => ""),
		array("id" => 6, "codeName" => "helm_of_iron_will", "localizedName" => ""),
		array("id" => 7, "codeName" => "javelin", "localizedName" => ""),
		array("id" => 8, "codeName" => "mithril_hammer", "localizedName" => ""),
		array("id" => 9, "codeName" => "platemail", "localizedName" => ""),
		array("id" => 10, "codeName" => "quarterstaff", "localizedName" => ""),
		array("id" => 11, "codeName" => "quelling_blade", "localizedName" => ""),
		array("id" => 12, "codeName" => "ring_of_protection", "localizedName" => ""),
		array("id" => 182, "codeName" => "stout_shield", "localizedName" => ""),
		array("id" => 13, "codeName" => "gauntlets", "localizedName" => ""),
		array("id" => 14, "codeName" => "slippers", "localizedName" => ""),
		array("id" => 15, "codeName" => "mantle", "localizedName" => ""),
		array("id" => 16, "codeName" => "branches", "localizedName" => ""),
		array("id" => 17, "codeName" => "belt_of_strength", "localizedName" => ""),
		array("id" => 18, "codeName" => "boots_of_elves", "localizedName" => ""),
		array("id" => 19, "codeName" => "robe", "localizedName" => ""),
		array("id" => 20, "codeName" => "circlet", "localizedName" => ""),
		array("id" => 21, "codeName" => "ogre_axe", "localizedName" => ""),
		array("id" => 22, "codeName" => "blade_of_alacrity", "localizedName" => ""),
		array("id" => 23, "codeName" => "staff_of_wizardry", "localizedName" => ""),
		array("id" => 24, "codeName" => "ultimate_orb", "localizedName" => ""),
		array("id" => 25, "codeName" => "gloves", "localizedName" => ""),
		array("id" => 26, "codeName" => "lifesteal", "localizedName" => ""),
		array("id" => 27, "codeName" => "ring_of_regen", "localizedName" => ""),
		array("id" => 28, "codeName" => "sobi_mask", "localizedName" => ""),
		array("id" => 29, "codeName" => "boots", "localizedName" => ""),
		array("id" => 30, "codeName" => "gem", "localizedName" => ""),
		array("id" => 31, "codeName" => "cloak", "localizedName" => ""),
		array("id" => 32, "codeName" => "talisman_of_evasion", "localizedName" => ""),
		array("id" => 33, "codeName" => "cheese", "localizedName" => ""),
		array("id" => 34, "codeName" => "magic_stick", "localizedName" => ""),
		array("id" => 35, "codeName" => "recipe_magic_wand", "localizedName" => ""),
		array("id" => 36, "codeName" => "magic_wand", "localizedName" => ""),
		array("id" => 37, "codeName" => "ghost", "localizedName" => ""),
		array("id" => 38, "codeName" => "clarity", "localizedName" => ""),
		array("id" => 39, "codeName" => "flask", "localizedName" => ""),
		array("id" => 40, "codeName" => "dust", "localizedName" => ""),
		array("id" => 41, "codeName" => "bottle", "localizedName" => ""),
		array("id" => 42, "codeName" => "ward_observer", "localizedName" => ""),
		array("id" => 43, "codeName" => "ward_sentry", "localizedName" => ""),
		array("id" => 44, "codeName" => "tango", "localizedName" => ""),
		array("id" => 45, "codeName" => "courier", "localizedName" => ""),
		array("id" => 46, "codeName" => "tpscroll", "localizedName" => ""),
		array("id" => 47, "codeName" => "recipe_travel_boots", "localizedName" => ""),
		array("id" => 48, "codeName" => "travel_boots", "localizedName" => ""),
		array("id" => 49, "codeName" => "recipe_phase_boots", "localizedName" => ""),
		array("id" => 50, "codeName" => "phase_boots", "localizedName" => ""),
		array("id" => 51, "codeName" => "demon_edge", "localizedName" => ""),
		array("id" => 52, "codeName" => "eagle", "localizedName" => ""),
		array("id" => 53, "codeName" => "reaver", "localizedName" => ""),
		array("id" => 54, "codeName" => "relic", "localizedName" => ""),
		array("id" => 55, "codeName" => "hyperstone", "localizedName" => ""),
		array("id" => 56, "codeName" => "ring_of_health", "localizedName" => ""),
		array("id" => 57, "codeName" => "void_stone", "localizedName" => ""),
		array("id" => 58, "codeName" => "mystic_staff", "localizedName" => ""),
		array("id" => 59, "codeName" => "energy_booster", "localizedName" => ""),
		array("id" => 60, "codeName" => "point_booster", "localizedName" => ""),
		array("id" => 61, "codeName" => "vitality_booster", "localizedName" => ""),
		array("id" => 62, "codeName" => "recipe_power_treads", "localizedName" => ""),
		array("id" => 63, "codeName" => "power_treads", "localizedName" => ""),
		array("id" => 64, "codeName" => "recipe_hand_of_midas", "localizedName" => ""),
		array("id" => 65, "codeName" => "hand_of_midas", "localizedName" => ""),
		array("id" => 66, "codeName" => "recipe_oblivion_staff", "localizedName" => ""),
		array("id" => 67, "codeName" => "oblivion_staff", "localizedName" => ""),
		array("id" => 68, "codeName" => "recipe_pers", "localizedName" => ""),
		array("id" => 69, "codeName" => "pers", "localizedName" => ""),
		array("id" => 70, "codeName" => "recipe_poor_mans_shield", "localizedName" => ""),
		array("id" => 71, "codeName" => "poor_mans_shield", "localizedName" => ""),
		array("id" => 72, "codeName" => "recipe_bracer", "localizedName" => ""),
		array("id" => 73, "codeName" => "bracer", "localizedName" => ""),
		array("id" => 74, "codeName" => "recipe_wraith_band", "localizedName" => ""),
		array("id" => 75, "codeName" => "wraith_band", "localizedName" => ""),
		array("id" => 76, "codeName" => "recipe_null_talisman", "localizedName" => ""),
		array("id" => 77, "codeName" => "null_talisman", "localizedName" => ""),
		array("id" => 78, "codeName" => "recipe_mekansm", "localizedName" => ""),
		array("id" => 79, "codeName" => "mekansm", "localizedName" => ""),
		array("id" => 80, "codeName" => "recipe_vladmir", "localizedName" => ""),
		array("id" => 81, "codeName" => "vladmir", "localizedName" => ""),
		array("id" => 84, "codeName" => "flying_courier", "localizedName" => ""),
		array("id" => 85, "codeName" => "recipe_buckler", "localizedName" => ""),
		array("id" => 86, "codeName" => "buckler", "localizedName" => ""),
		array("id" => 87, "codeName" => "recipe_ring_of_basilius", "localizedName" => ""),
		array("id" => 88, "codeName" => "ring_of_basilius", "localizedName" => ""),
		array("id" => 89, "codeName" => "recipe_pipe", "localizedName" => ""),
		array("id" => 90, "codeName" => "pipe", "localizedName" => ""),
		array("id" => 91, "codeName" => "recipe_urn_of_shadows", "localizedName" => ""),
		array("id" => 92, "codeName" => "urn_of_shadows", "localizedName" => ""),
		array("id" => 93, "codeName" => "recipe_headdress", "localizedName" => ""),
		array("id" => 94, "codeName" => "headdress", "localizedName" => ""),
		array("id" => 95, "codeName" => "recipe_sheepstick", "localizedName" => ""),
		array("id" => 96, "codeName" => "sheepstick", "localizedName" => ""),
		array("id" => 97, "codeName" => "recipe_orchid", "localizedName" => ""),
		array("id" => 98, "codeName" => "orchid", "localizedName" => ""),
		array("id" => 99, "codeName" => "recipe_cyclone", "localizedName" => ""),
		array("id" => 100, "codeName" => "cyclone", "localizedName" => ""),
		array("id" => 101, "codeName" => "recipe_force_staff", "localizedName" => ""),
		array("id" => 102, "codeName" => "force_staff", "localizedName" => ""),
		array("id" => 103, "codeName" => "recipe_dagon", "localizedName" => ""),
		array("id" => 197, "codeName" => "recipe_dagon_2", "localizedName" => ""),
		array("id" => 198, "codeName" => "recipe_dagon_3", "localizedName" => ""),
		array("id" => 199, "codeName" => "recipe_dagon_4", "localizedName" => ""),
		array("id" => 200, "codeName" => "recipe_dagon_5", "localizedName" => ""),
		array("id" => 104, "codeName" => "dagon", "localizedName" => "Dagon niv. 1"),
		array("id" => 201, "codeName" => "dagon_2", "localizedName" => "Dagon niv. 2"),
		array("id" => 202, "codeName" => "dagon_3", "localizedName" => "Dagon niv. 3"),
		array("id" => 203, "codeName" => "dagon_4", "localizedName" => ""),
		array("id" => 204, "codeName" => "dagon_5", "localizedName" => ""),
		array("id" => 105, "codeName" => "recipe_necronomicon", "localizedName" => ""),
		array("id" => 191, "codeName" => "recipe_necronomicon_2", "localizedName" => ""),
		array("id" => 192, "codeName" => "recipe_necronomicon_3", "localizedName" => ""),
		array("id" => 106, "codeName" => "necronomicon", "localizedName" => ""),
		array("id" => 193, "codeName" => "necronomicon_2", "localizedName" => ""),
		array("id" => 194, "codeName" => "necronomicon_3", "localizedName" => ""),
		array("id" => 107, "codeName" => "recipe_ultimate_scepter", "localizedName" => ""),
		array("id" => 108, "codeName" => "ultimate_scepter", "localizedName" => ""),
		array("id" => 109, "codeName" => "recipe_refresher", "localizedName" => ""),
		array("id" => 110, "codeName" => "refresher", "localizedName" => ""),
		array("id" => 111, "codeName" => "recipe_assault", "localizedName" => ""),
		array("id" => 112, "codeName" => "assault", "localizedName" => ""),
		array("id" => 113, "codeName" => "recipe_heart", "localizedName" => ""),
		array("id" => 114, "codeName" => "heart", "localizedName" => ""),
		array("id" => 115, "codeName" => "recipe_black_king_bar", "localizedName" => ""),
		array("id" => 116, "codeName" => "black_king_bar", "localizedName" => ""),
		array("id" => 117, "codeName" => "aegis", "localizedName" => ""),
		array("id" => 118, "codeName" => "recipe_shivas_guard", "localizedName" => ""),
		array("id" => 119, "codeName" => "shivas_guard", "localizedName" => ""),
		array("id" => 120, "codeName" => "recipe_bloodstone", "localizedName" => ""),
		array("id" => 121, "codeName" => "bloodstone", "localizedName" => ""),
		array("id" => 122, "codeName" => "recipe_sphere", "localizedName" => ""),
		array("id" => 123, "codeName" => "sphere", "localizedName" => ""),
		array("id" => 124, "codeName" => "recipe_vanguard", "localizedName" => ""),
		array("id" => 125, "codeName" => "vanguard", "localizedName" => ""),
		array("id" => 126, "codeName" => "recipe_blade_mail", "localizedName" => ""),
		array("id" => 127, "codeName" => "blade_mail", "localizedName" => ""),
		array("id" => 128, "codeName" => "recipe_soul_booster", "localizedName" => ""),
		array("id" => 129, "codeName" => "soul_booster", "localizedName" => ""),
		array("id" => 130, "codeName" => "recipe_hood_of_defiance", "localizedName" => ""),
		array("id" => 131, "codeName" => "hood_of_defiance", "localizedName" => ""),
		array("id" => 132, "codeName" => "recipe_rapier", "localizedName" => ""),
		array("id" => 133, "codeName" => "rapier", "localizedName" => ""),
		array("id" => 134, "codeName" => "recipe_monkey_king_bar", "localizedName" => ""),
		array("id" => 135, "codeName" => "monkey_king_bar", "localizedName" => ""),
		array("id" => 136, "codeName" => "recipe_radiance", "localizedName" => ""),
		array("id" => 137, "codeName" => "radiance", "localizedName" => ""),
		array("id" => 138, "codeName" => "recipe_butterfly", "localizedName" => ""),
		array("id" => 139, "codeName" => "butterfly", "localizedName" => ""),
		array("id" => 140, "codeName" => "recipe_greater_crit", "localizedName" => ""),
		array("id" => 141, "codeName" => "greater_crit", "localizedName" => ""),
		array("id" => 142, "codeName" => "recipe_basher", "localizedName" => ""),
		array("id" => 143, "codeName" => "basher", "localizedName" => ""),
		array("id" => 144, "codeName" => "recipe_bfury", "localizedName" => ""),
		array("id" => 145, "codeName" => "bfury", "localizedName" => ""),
		array("id" => 146, "codeName" => "recipe_manta", "localizedName" => ""),
		array("id" => 147, "codeName" => "manta", "localizedName" => ""),
		array("id" => 148, "codeName" => "recipe_lesser_crit", "localizedName" => ""),
		array("id" => 149, "codeName" => "lesser_crit", "localizedName" => ""),
		array("id" => 150, "codeName" => "recipe_armlet", "localizedName" => ""),
		array("id" => 151, "codeName" => "armlet", "localizedName" => ""),
		array("id" => 183, "codeName" => "recipe_invis_sword", "localizedName" => ""),
		array("id" => 152, "codeName" => "invis_sword", "localizedName" => ""),
		array("id" => 153, "codeName" => "recipe_sange_and_yasha", "localizedName" => ""),
		array("id" => 154, "codeName" => "sange_and_yasha", "localizedName" => ""),
		array("id" => 155, "codeName" => "recipe_satanic", "localizedName" => ""),
		array("id" => 156, "codeName" => "satanic", "localizedName" => ""),
		array("id" => 157, "codeName" => "recipe_mjollnir", "localizedName" => ""),
		array("id" => 158, "codeName" => "mjollnir", "localizedName" => ""),
		array("id" => 159, "codeName" => "recipe_skadi", "localizedName" => ""),
		array("id" => 160, "codeName" => "skadi", "localizedName" => ""),
		array("id" => 161, "codeName" => "recipe_sange", "localizedName" => ""),
		array("id" => 162, "codeName" => "sange", "localizedName" => ""),
		array("id" => 163, "codeName" => "recipe_helm_of_the_dominator", "localizedName" => ""),
		array("id" => 164, "codeName" => "helm_of_the_dominator", "localizedName" => ""),
		array("id" => 165, "codeName" => "recipe_maelstrom", "localizedName" => ""),
		array("id" => 166, "codeName" => "maelstrom", "localizedName" => ""),
		array("id" => 167, "codeName" => "recipe_desolator", "localizedName" => ""),
		array("id" => 168, "codeName" => "desolator", "localizedName" => ""),
		array("id" => 169, "codeName" => "recipe_yasha", "localizedName" => ""),
		array("id" => 170, "codeName" => "yasha", "localizedName" => ""),
		array("id" => 171, "codeName" => "recipe_mask_of_madness", "localizedName" => ""),
		array("id" => 172, "codeName" => "mask_of_madness", "localizedName" => ""),
		array("id" => 173, "codeName" => "recipe_diffusal_blade", "localizedName" => ""),
		array("id" => 195, "codeName" => "recipe_diffusal_blade_2", "localizedName" => ""),
		array("id" => 174, "codeName" => "diffusal_blade", "localizedName" => ""),
		array("id" => 196, "codeName" => "recipe_diffusal_blade_2", "localizedName" => ""),
		array("id" => 175, "codeName" => "recipe_ethereal_blade", "localizedName" => ""),
		array("id" => 176, "codeName" => "ethereal_blade", "localizedName" => ""),
		array("id" => 177, "codeName" => "recipe_soul_ring", "localizedName" => ""),
		array("id" => 178, "codeName" => "soul_ring", "localizedName" => ""),
		array("id" => 179, "codeName" => "recipe_arcane_boots", "localizedName" => ""),
		array("id" => 180, "codeName" => "arcane_boots", "localizedName" => ""),
		array("id" => 181, "codeName" => "orb_of_venom", "localizedName" => ""),
		array("id" => 184, "codeName" => "recipe_ancient_janggo", "localizedName" => ""),
		array("id" => 185, "codeName" => "ancient_janggo", "localizedName" => ""),
		array("id" => 186, "codeName" => "recipe_medallion_of_courage", "localizedName" => ""),
		array("id" => 187, "codeName" => "medallion_of_courage", "localizedName" => ""),
		array("id" => 188, "codeName" => "smoke_of_deceit", "localizedName" => ""),
		array("id" => 189, "codeName" => "recipe_veil_of_discord", "localizedName" => ""),
		array("id" => 190, "codeName" => "veil_of_discord", "localizedName" => ""),
		array("id" => 205, "codeName" => "recipe_rod_of_atos", "localizedName" => ""),
		array("id" => 206, "codeName" => "rod_of_atos", "localizedName" => ""),
		array("id" => 207, "codeName" => "recipe_abyssal_blade", "localizedName" => ""),
		array("id" => 208, "codeName" => "abyssal_blade", "localizedName" => ""),
		array("id" => 209, "codeName" => "recipe_heavens_halberd", "localizedName" => ""),
		array("id" => 210, "codeName" => "heavens_halberd", "localizedName" => ""),
		array("id" => 211, "codeName" => "recipe_ring_of_aquila", "localizedName" => ""),
		array("id" => 212, "codeName" => "ring_of_aquila", "localizedName" => ""),
		array("id" => 213, "codeName" => "recipe_tranquil_boots", "localizedName" => ""),
		array("id" => 214, "codeName" => "tranquil_boots", "localizedName" => ""),
		array("id" => 215, "codeName" => "shadow_amulet", "localizedName" => ""),
		array("id" => 216, "codeName" => "halloween_candy_corn", "localizedName" => ""),
		array("id" => 217, "codeName" => "mystery_hook", "localizedName" => ""),
		array("id" => 218, "codeName" => "mystery_arrow", "localizedName" => ""),
		array("id" => 219, "codeName" => "mystery_missile", "localizedName" => ""),
		array("id" => 220, "codeName" => "mystery_toss", "localizedName" => ""),
		array("id" => 221, "codeName" => "mystery_vacuum", "localizedName" => ""),
		array("id" => 226, "codeName" => "halloween_rapier", "localizedName" => ""),
		array("id" => 228, "codeName" => "greevil_whistle", "localizedName" => ""),
		array("id" => 235, "codeName" => "greevil_whistle_toggle", "localizedName" => ""),
		array("id" => 227, "codeName" => "present", "localizedName" => ""),
		array("id" => 229, "codeName" => "winter_stocking", "localizedName" => ""),
		array("id" => 230, "codeName" => "winter_skates", "localizedName" => ""),
		array("id" => 231, "codeName" => "winter_cake", "localizedName" => ""),
		array("id" => 232, "codeName" => "winter_cookie", "localizedName" => ""),
		array("id" => 233, "codeName" => "winter_coco", "localizedName" => ""),
		array("id" => 234, "codeName" => "winter_ham", "localizedName" => ""),
		array("id" => 236, "codeName" => "winter_kringle", "localizedName" => ""),
		array("id" => 237, "codeName" => "winter_mushroom", "localizedName" => ""),
		array("id" => 238, "codeName" => "winter_greevil_treat", "localizedName" => ""),
		array("id" => 239, "codeName" => "winter_greevil_garbage", "localizedName" => ""),
		array("id" => 240, "codeName" => "winter_greevil_chewy", "localizedName" => ""),
		array("id" => 241, "codeName" => "tango_single", "localizedName" => "Tango partagé"),
		array("id" => 242, "codeName" => "crimson_guard", "localizedName" => "Crimson guard"),

	);

}